name = "CuCountmap"
uuid = "7f9ef4d9-b8e2-47f5-be66-f1ea02ff3f4a"
authors = ["evalparse <zhuojia.dai@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
